server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/nowstar?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: root123
  jpa:
    database: mysql
    #配置数据库引擎和字符集
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    #配置自动建表：updata:没有表新建，有表更新操作
    hibernate:
      ddl-auto: update
    #控制台显示建表语句
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}